# -*- coding: utf-8 -*-
"""4 задание.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cfWZCJE9IFWWxyTslnSChLjuG4rf4EY
"""

import pygal.maps.world

# Создание карты
worldmap_chart = pygal.maps.world.World()

# Заголовок
worldmap_chart.title = 'Currency Stability'

# Страны
worldmap_chart.add('Stable', {'us': 1, 'ca': 1, 'gb': 1, 'au': 1, 'nz': 1, 'ch': 1, 'jp': 1, 'sg': 1, 'hk': 1, 'kr': 1, 'se': 1, 'no': 1, 'dk': 1, 'fi': 1, 'nl': 1, 'be': 1, 'lu': 1, 'de': 1, 'at': 1, 'fr': 1, 'it': 1, 'es': 1, 'pt': 1, 'ie': 1, 'gr': 1, 'cz': 1, 'sk': 1, 'hu': 1, 'pl': 1, 'ro': 1, 'bg': 1, 'hr': 1, 'rs': 1, 'si': 1, 'ee': 1, 'lv': 1, 'lt': 1, 'is': 1})
worldmap_chart.add('Neutral', {'cn': 1, 'in': 1, 'br': 1, 'mx': 1, 'ru': 1, 'tr': 1, 'id': 1, 'my': 1, 'th': 1, 'ph': 1, 'vn': 1, 'za': 1, 'eg': 1, 'ng': 1, 'ke': 1, 'et': 1, 'dz': 1, 'ma': 1, 'tn': 1, 'ly': 1, 'sd': 1, 'iq': 1, 'ir': 1, 'sa': 1, 'ae': 1, 'il': 1})
worldmap_chart.add('Unstable', {'ve': 1, 'co': 1, 'pe': 1, 'cl': 1, 'ar': 1, 'ec': 1, 'bo': 1, 'py': 1, 'uy': 1})

# Рендер
worldmap_chart.render_in_browser()

